Kendal_spark_implementation
ydataai/pandas-profiling pull request #1084
Opened 2022-09-30 14:26 UTC by rishabsinghh

I have implemented Kendal's Correlation using spark. There are still some optimizations to be made. But for now this works.

2022-09-30 18:09 UTC, fabclmnt requested changes
@rishabsinghh please create the PR to the `spark-branck`. Currently, no spark development is yet available in develop and master branches. 

Also, can you please update you PR commit message to follow the expected commit format, for example:
'feat: (description)'

2022-10-02 01:03 UTC, sbrugman commented on src/pandas_profiling/model/pandas/correlations_pandas.py
> +from collections import defaultdict
Please run the pre-commit hooks

2022-10-02 01:04 UTC, sbrugman commented on src/pandas_profiling/model/pandas/correlations_pandas.py
> +
The spark implementation should be placed in `src/pandas_profiling/model/spark/correlation_spark.py`

2022-10-25 04:21 UTC, chanedwin commented
@rishabsinghh please change the PR's branch to feat/spark-minimal, thanks###

2022-12-11 15:27 UTC, chanedwin commented
moved over to https://github.com/ydataai/pandas-profiling/pull/1205

2022-12-11 15:27 UTC, closed without merging