fix(html): sensible cloud-platform notebook html rendering
ydataai/pandas-profiling pull request #1178
Opened 2022-11-27 05:05 UTC by rivanfebrian123

# Variables
In current version, if we click a variable, it will cause strange errors.
![图片](https://user-images.githubusercontent.com/6300910/204118317-946f5358-b921-481b-9a51-53eb3de74dd3.png)

**On Google Colab:**
Notebook: https://colab.research.google.com/drive/1cksGQIhby5ht8hOcC4szCoTSz1IgF1O3?usp=sharing
![图片](https://user-images.githubusercontent.com/6300910/204118348-c8367c47-9eae-4f1f-ae9c-1bb771a20cd3.png)

**On Binder:**
Notebook: https://mybinder.org/v2/gist/rivanfebrian123/21fed85603a8ada2435d452a27de287e/HEAD?labpath=EDA%20Pandas%20Profiling.ipynb
![图片](https://user-images.githubusercontent.com/6300910/204118893-57dcaf0d-4d88-4d38-aeb7-d9f14cb12d59.png)

# Links
On the other hand, when we click a link, it will open inside the iframe instead of a new tab:
![图片](https://user-images.githubusercontent.com/6300910/204118979-0e3c450a-f4aa-431a-94d4-cecd738612bf.png)
![图片](https://user-images.githubusercontent.com/6300910/204119214-ca7d600c-653a-45bf-98af-6635df507d32.png)

**On Google Colab:**
![图片](https://user-images.githubusercontent.com/6300910/204119234-f0bdab15-95ae-4392-8fb3-733ad6aa3279.png)

# Solution
To fix those HTML rendering troubles, I changed the default anchoring behaviors to the more sensible ones.

2022-11-27 20:02 UTC, fabclmnt commented on .github/workflows/pull-request.yml
>  jobs:
@rivanfebrian123 Can you please revert this change?

2022-11-28 15:08 UTC, aquemy requested changes
Just a small rebase from develop

2022-11-28 22:31 UTC, rivanfebrian123 commented on src/pandas_profiling/utils/cache.py
>  import zipfile
Done!

2022-11-30 10:56 UTC, rivanfebrian123 commented
*11月30日 下午 5:56 WIB*


Re-sync to `ydataai:develop` like in #1185

2022-12-06 07:56 UTC, aquemy approved these changes

2022-12-06 10:05 UTC, merged